// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/presentation/cubit/tv_series/tv_series_detail_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:core/domain/entities/tv_series/episode.dart' as _i11;
import 'package:core/domain/entities/tv_series/tv_series.dart' as _i9;
import 'package:core/domain/entities/tv_series/tv_series_detail.dart' as _i7;
import 'package:core/domain/repositories/tv_series_repository.dart' as _i2;
import 'package:core/domain/usecases/tv_series/get_detail_tv_series.dart'
    as _i4;
import 'package:core/domain/usecases/tv_series/get_recommendation_tv_series.dart'
    as _i8;
import 'package:core/domain/usecases/tv_series/get_tv_series_episode.dart'
    as _i10;
import 'package:core/utils/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTvSeriesRepository_0 extends _i1.Fake
    implements _i2.TvSeriesRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetDetailTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDetailTvSeries extends _i1.Mock implements _i4.GetDetailTvSeries {
  MockGetDetailTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSeriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvSeriesRepository_0()) as _i2.TvSeriesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TvSeriesDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, _i7.TvSeriesDetail>>.value(
                      _FakeEither_1<_i6.Failure, _i7.TvSeriesDetail>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.TvSeriesDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetRecommendationTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecommendationTvSeries extends _i1.Mock
    implements _i8.GetRecommendationTvSeries {
  MockGetRecommendationTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSeriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvSeriesRepository_0()) as _i2.TvSeriesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvSeries>>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i9.TvSeries>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i9.TvSeries>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvSeries>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetTvSeriesEpisode].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeriesEpisode extends _i1.Mock
    implements _i10.GetTvSeriesEpisode {
  MockGetTvSeriesEpisode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSeriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvSeriesRepository_0()) as _i2.TvSeriesRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i11.Episode>>> execute(
          int? id, int? season) =>
      (super.noSuchMethod(Invocation.method(#execute, [id, season]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i11.Episode>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i11.Episode>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i11.Episode>>>);
  @override
  String toString() => super.toString();
}
