// Mocks generated by Mockito 5.0.16 from annotations
// in search/test/presentation/pages/tv_series/search_tv_series_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:search/domain/usecases/tv_series/search_tv_series.dart' as _i2;
import 'package:search/presentation/cubit/tv_series/search_tv_series_cubit.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSearchTvSeries_0 extends _i1.Fake implements _i2.SearchTvSeries {}

class _FakeSearchTvSeriesState_1 extends _i1.Fake
    implements _i3.SearchTvSeriesState {}

class _FakeStreamSubscription_2<T> extends _i1.Fake
    implements _i4.StreamSubscription<T> {}

/// A class which mocks [SearchTvSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTvSeriesCubit extends _i1.Mock
    implements _i3.SearchTvSeriesCubit {
  MockSearchTvSeriesCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchTvSeries get searchTvSeries =>
      (super.noSuchMethod(Invocation.getter(#searchTvSeries),
          returnValue: _FakeSearchTvSeries_0()) as _i2.SearchTvSeries);
  @override
  _i3.SearchTvSeriesState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeSearchTvSeriesState_1()) as _i3.SearchTvSeriesState);
  @override
  _i4.Stream<_i3.SearchTvSeriesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.SearchTvSeriesState>.empty())
          as _i4.Stream<_i3.SearchTvSeriesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void fetchSearchTvSeries(String? query) =>
      super.noSuchMethod(Invocation.method(#fetchSearchTvSeries, [query]),
          returnValueForMissingStub: null);
  @override
  _i4.StreamSubscription<_i3.SearchTvSeriesState> listen(
          void Function(_i3.SearchTvSeriesState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_2<_i3.SearchTvSeriesState>())
          as _i4.StreamSubscription<_i3.SearchTvSeriesState>);
  @override
  void emit(_i3.SearchTvSeriesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i5.Change<_i3.SearchTvSeriesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
