// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/presentation/pages/tv_series/tv_series_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i12;
import 'package:core/domain/entities/movie/movie.dart' as _i13;
import 'package:core/domain/usecases/get_watchlist.dart' as _i7;
import 'package:core/domain/usecases/get_watchlist_status.dart' as _i8;
import 'package:core/domain/usecases/remove_watchlist.dart' as _i10;
import 'package:core/domain/usecases/save_watchlist.dart' as _i9;
import 'package:core/domain/usecases/tv_series/get_detail_tv_series.dart'
    as _i2;
import 'package:core/domain/usecases/tv_series/get_recommendation_tv_series.dart'
    as _i3;
import 'package:core/domain/usecases/tv_series/get_tv_series_episode.dart'
    as _i4;
import 'package:core/presentation/cubit/tv_series/tv_series_detail_cubit.dart'
    as _i5;
import 'package:core/presentation/cubit/watchlist_cubit.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetDetailTvSeries_0 extends _i1.Fake
    implements _i2.GetDetailTvSeries {}

class _FakeGetRecommendationTvSeries_1 extends _i1.Fake
    implements _i3.GetRecommendationTvSeries {}

class _FakeGetTvSeriesEpisode_2 extends _i1.Fake
    implements _i4.GetTvSeriesEpisode {}

class _FakeTvSeriesDetailState_3 extends _i1.Fake
    implements _i5.TvSeriesDetailState {}

class _FakeStreamSubscription_4<T> extends _i1.Fake
    implements _i6.StreamSubscription<T> {}

class _FakeGetWatchlist_5 extends _i1.Fake implements _i7.GetWatchlist {}

class _FakeGetWatchListStatus_6 extends _i1.Fake
    implements _i8.GetWatchListStatus {}

class _FakeSaveWatchlist_7 extends _i1.Fake implements _i9.SaveWatchlist {}

class _FakeRemoveWatchlist_8 extends _i1.Fake implements _i10.RemoveWatchlist {}

class _FakeWatchlistState_9 extends _i1.Fake implements _i11.WatchlistState {}

/// A class which mocks [TvSeriesDetailCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailCubit extends _i1.Mock
    implements _i5.TvSeriesDetailCubit {
  MockTvSeriesDetailCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetDetailTvSeries get detailTvSeries =>
      (super.noSuchMethod(Invocation.getter(#detailTvSeries),
          returnValue: _FakeGetDetailTvSeries_0()) as _i2.GetDetailTvSeries);
  @override
  _i3.GetRecommendationTvSeries get recommendationTvSeries =>
      (super.noSuchMethod(Invocation.getter(#recommendationTvSeries),
              returnValue: _FakeGetRecommendationTvSeries_1())
          as _i3.GetRecommendationTvSeries);
  @override
  _i4.GetTvSeriesEpisode get tvSeriesEpisode =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesEpisode),
          returnValue: _FakeGetTvSeriesEpisode_2()) as _i4.GetTvSeriesEpisode);
  @override
  _i5.TvSeriesDetailState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeTvSeriesDetailState_3()) as _i5.TvSeriesDetailState);
  @override
  _i6.Stream<_i5.TvSeriesDetailState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i5.TvSeriesDetailState>.empty())
          as _i6.Stream<_i5.TvSeriesDetailState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void fetchDetailTv(int? id) =>
      super.noSuchMethod(Invocation.method(#fetchDetailTv, [id]),
          returnValueForMissingStub: null);
  @override
  void fetchEpisodeTv(int? id, int? season) =>
      super.noSuchMethod(Invocation.method(#fetchEpisodeTv, [id, season]),
          returnValueForMissingStub: null);
  @override
  _i6.StreamSubscription<_i5.TvSeriesDetailState> listen(
          void Function(_i5.TvSeriesDetailState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_4<_i5.TvSeriesDetailState>())
          as _i6.StreamSubscription<_i5.TvSeriesDetailState>);
  @override
  void emit(_i5.TvSeriesDetailState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i12.Change<_i5.TvSeriesDetailState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [WatchlistCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistCubit extends _i1.Mock implements _i11.WatchlistCubit {
  MockWatchlistCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GetWatchlist get watchlist =>
      (super.noSuchMethod(Invocation.getter(#watchlist),
          returnValue: _FakeGetWatchlist_5()) as _i7.GetWatchlist);
  @override
  _i8.GetWatchListStatus get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
          returnValue: _FakeGetWatchListStatus_6()) as _i8.GetWatchListStatus);
  @override
  _i9.SaveWatchlist get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
          returnValue: _FakeSaveWatchlist_7()) as _i9.SaveWatchlist);
  @override
  _i10.RemoveWatchlist get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
          returnValue: _FakeRemoveWatchlist_8()) as _i10.RemoveWatchlist);
  @override
  _i11.WatchlistState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeWatchlistState_9()) as _i11.WatchlistState);
  @override
  _i6.Stream<_i11.WatchlistState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i11.WatchlistState>.empty())
          as _i6.Stream<_i11.WatchlistState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void loadWatchlistStatus(int? id) =>
      super.noSuchMethod(Invocation.method(#loadWatchlistStatus, [id]),
          returnValueForMissingStub: null);
  @override
  void fetchWatchlist() =>
      super.noSuchMethod(Invocation.method(#fetchWatchlist, []),
          returnValueForMissingStub: null);
  @override
  void addWatchlist(_i13.Movie? movie) =>
      super.noSuchMethod(Invocation.method(#addWatchlist, [movie]),
          returnValueForMissingStub: null);
  @override
  void deleteWatchlist(int? id) =>
      super.noSuchMethod(Invocation.method(#deleteWatchlist, [id]),
          returnValueForMissingStub: null);
  @override
  _i6.StreamSubscription<_i11.WatchlistState> listen(
          void Function(_i11.WatchlistState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_4<_i11.WatchlistState>())
          as _i6.StreamSubscription<_i11.WatchlistState>);
  @override
  void emit(_i11.WatchlistState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i12.Change<_i11.WatchlistState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  String toString() => super.toString();
}
