// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/presentation/pages/tv_series/tv_series_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i10;
import 'dart:ui' as _i11;

import 'package:core/core.dart' as _i7;
import 'package:core/domain/entities/tv_series/episode.dart' as _i9;
import 'package:core/domain/entities/tv_series/tv_series.dart' as _i8;
import 'package:core/domain/entities/tv_series/tv_series_detail.dart' as _i5;
import 'package:core/domain/usecases/tv_series/get_detail_tv_series.dart'
    as _i2;
import 'package:core/domain/usecases/tv_series/get_recommendation_tv_series.dart'
    as _i3;
import 'package:core/domain/usecases/tv_series/get_tv_series_episode.dart'
    as _i4;
import 'package:core/presentation/provider/tv_series/tv_series_detail_notifier.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetDetailTvSeries_0 extends _i1.Fake
    implements _i2.GetDetailTvSeries {}

class _FakeGetRecommendationTvSeries_1 extends _i1.Fake
    implements _i3.GetRecommendationTvSeries {}

class _FakeGetTvSeriesEpisode_2 extends _i1.Fake
    implements _i4.GetTvSeriesEpisode {}

class _FakeTvSeriesDetail_3 extends _i1.Fake implements _i5.TvSeriesDetail {}

/// A class which mocks [TvSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailNotifier extends _i1.Mock
    implements _i6.TvSeriesDetailNotifier {
  MockTvSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetDetailTvSeries get getDetailTvSeries =>
      (super.noSuchMethod(Invocation.getter(#getDetailTvSeries),
          returnValue: _FakeGetDetailTvSeries_0()) as _i2.GetDetailTvSeries);
  @override
  _i3.GetRecommendationTvSeries get getRecommendationTvSeries =>
      (super.noSuchMethod(Invocation.getter(#getRecommendationTvSeries),
              returnValue: _FakeGetRecommendationTvSeries_1())
          as _i3.GetRecommendationTvSeries);
  @override
  _i4.GetTvSeriesEpisode get getTvSeriesEpisode =>
      (super.noSuchMethod(Invocation.getter(#getTvSeriesEpisode),
          returnValue: _FakeGetTvSeriesEpisode_2()) as _i4.GetTvSeriesEpisode);
  @override
  _i5.TvSeriesDetail get tvSeriesDetail =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesDetail),
          returnValue: _FakeTvSeriesDetail_3()) as _i5.TvSeriesDetail);
  @override
  _i7.RequestState get tvSeriesState =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesState),
          returnValue: _i7.RequestState.empty) as _i7.RequestState);
  @override
  List<_i8.TvSeries> get recomendedTvSeries =>
      (super.noSuchMethod(Invocation.getter(#recomendedTvSeries),
          returnValue: <_i8.TvSeries>[]) as List<_i8.TvSeries>);
  @override
  _i7.RequestState get recommendedState =>
      (super.noSuchMethod(Invocation.getter(#recommendedState),
          returnValue: _i7.RequestState.empty) as _i7.RequestState);
  @override
  List<_i9.Episode> get episodeTvSeries =>
      (super.noSuchMethod(Invocation.getter(#episodeTvSeries),
          returnValue: <_i9.Episode>[]) as List<_i9.Episode>);
  @override
  _i7.RequestState get episodeState =>
      (super.noSuchMethod(Invocation.getter(#episodeState),
          returnValue: _i7.RequestState.empty) as _i7.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i10.Future<void> fetchTvSeriesDetail(int? id) => (super.noSuchMethod(
      Invocation.method(#fetchTvSeriesDetail, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i10.Future<void>);
  @override
  _i10.Future<void> fetchTvSeriesEpisode(int? id, int? season) => (super
          .noSuchMethod(Invocation.method(#fetchTvSeriesEpisode, [id, season]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
      as _i10.Future<void>);
  @override
  void addListener(_i11.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i11.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
